version: '3.9'

services:
  database:
    image: postgres:15.4
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=rwa'
      - 'POSTGRES_PASSWORD=rwa'
      - 'POSTGRES_DB=rwa'
      - "POSTGRES_INITDB_ARGS='--encoding=UTF-8'"